apiVersion: v1
kind: Service
metadata:
  name: company-service
spec:
  selector:
    app: company-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer  # Ou NodePort
